source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

pod 'AFNetworking', '~> 2.6'
pod 'MBProgressHUD', '~> 0.9'
pod 'WYPopoverController', '~> 0.3'
pod 'JSONModel', '~> 1.1'
pod 'MagicalRecord', '~> 2.3'
pod 'KLCPopup', '~> 1.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'